[build]
pre-build = []

[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/cross:x86_64-unknown-linux-gnu-latest"

[target.x86_64-unknown-linux-musl]
image = "ghcr.io/cross-rs/cross:x86_64-unknown-linux-musl-latest"

[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/cross:aarch64-unknown-linux-gnu-latest"

[target.aarch64-unknown-linux-musl]
image = "ghcr.io/cross-rs/cross:aarch64-unknown-linux-musl-latest"
